fix(react-day-picker): fix labelDay function to properly pick up the locale
gpbl/react-day-picker pull request #1301
Opened 2021-11-30 21:28 UTC by tjfred35

This becomes a typescript error when we more strongly type ModifierStatus (the second parameter) -- see https://github.com/gpbl/react-day-picker/pull/1299.

2021-11-30 21:29 UTC, tjfred35 commented on packages/react-day-picker/src/components/Day/Day.test.tsx
> +    expect(container).toHaveTextContent('18º noviembre (jueves)');
This is the test that was failing for me before the fix to the parameters below.

2021-12-01 11:14 UTC, gpbl requested changes
Thanks! 

Please remove the test, which will be done eventually for `labelDay` ("expect that `format` is called with options`).

2021-12-01 13:02 UTC, tjfred35 commented
I had a feeling you wouldn't like this test. Anyway, I've fixed it here too: https://github.com/gpbl/react-day-picker/pull/1299. So I'll close this PR.

2021-12-01 13:02 UTC, closed without merging

2021-12-01 13:27 UTC, gpbl commented
> 



> I had a feeling you wouldn't like this test.

 already thinking to a eslint plugin to help sharing these best practices 🦹🏼‍♀️