Unified example code on website regarding useState hooks
gpbl/react-day-picker pull request #2231
Opened 2024-06-24 18:11 UTC by dave-meyer

## Description

The previous code examples on the website sometimes used untyped 'useState' hooks. This made it sometimes difficult to understand the code. My changes add strong typing (i.e. ``useState<Date>()``) to wherever the code was not self explanatory.

Also, these changes unify the code examples, since some of them had strongly typed hooks and others did not.

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

Before submitting your pull request, please make sure the following is done:

- [x] I have read the [CONTRIBUTING](./CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works (not needed)
- [x] I have added necessary documentation (if appropriate)
- [x] I have followed the coding guidelines in this project
- [ ] I have tested my changes on different browsers and screen sizes (not needed)

## Linked Issues

None

## Test Plan

Not needed

## Screenshots (if appropriate)

Not needed

## Further Comments

None

2024-07-02 15:36 UTC, dave-meyer commented
I think this PR is ready for review/merge now.

2024-07-07 18:23 UTC, gpbl requested changes
Thanks a lot for your update. Not all the changes are correct, however - would you mind to fix these? Thanks again.

2024-07-07 18:23 UTC, gpbl commented on README.md
> +  const [selected, setSelected] = useState<Date>();
Single mode allows also `undefined` values.

```suggestion
  const [selected, setSelected] = useState<Date | undefined>();
```

2024-07-07 18:23 UTC, gpbl commented on website/docs/start.mdx
> +  const [selected, setSelected] = useState<Date>();
```suggestion
  const [selected, setSelected] = useState<Date | undefined>();
```

2024-07-07 18:23 UTC, gpbl commented on website/docs/using-daypicker/navigation.mdx
> +  const [month, setMonth] = useState<Date>(nextMonth);
Isn't this inferred already?

```suggestion
  const [month, setMonth] = useState(nextMonth);
```

2024-07-07 18:23 UTC, gpbl commented on website/docs/using-daypicker/selection-modes.mdx
> +  const [selectedDate, setSelectedDate] = useState<Date>(initiallySelectedDate);
This should also be inferred by the type of `initiallySelectedDate`.

```suggestion
  const [selectedDate, setSelectedDate] = useState(initiallySelectedDate);
```

2024-07-07 18:23 UTC, gpbl commented on website/docs/using-daypicker/selection-modes.mdx
> +  const [selected, setSelected] = useState<Date | undefined>();
This should be an array.

```suggestion
  const [selected, setSelected] = useState<Date[] | undefined>();
```

2024-07-07 21:23 UTC, dave-meyer commented
Thank you for reviewing! I commited your requested changes.

2024-07-07 21:47 UTC, gpbl approved these changes

2024-07-07 21:47 UTC, gpbl commented
Thanks _you_, @dave-meyer !

2024-07-07 21:47 UTC, merged